=== lauraParaschivescu/Map_Project/iteratia10/Positions.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Positions.namespace" xmlns="urn:Positions.namespace">
    <xs:element name="positions" type="positionsType"/>
    <xs:complexType name="positionsType">
        <xs:sequence>
            <xs:element type="positionType" name="position" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="positionType">
        <xs:sequence>
            <xs:element type="xs:string" name="name"/>
            <xs:element type="xs:string" name="type">
            </xs:element>
        </xs:sequence>
        <xs:attribute type="xs:int" name="id" use="required"/>
    </xs:complexType>
</xs:schema>

=== lauraParaschivescu/Map_Project/iteratia10/Positions.xml
<?xml version="1.0"?>
<positions xmlns="urn:Positions.namespace"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="urn:Positions.namespace Positions.xsd">
    <position id="1">
        <name>Ajutor programator</name>
        <type>Full-time</type>
    </position>
    <position id="2">
    <name>Ajutor bucatar1</name>
    <type>Full-time1</type>
    </position>
    <position id="3">
    <name>Bucatar</name>
    <type>Part-time</type>
    </position>
    <position id="90">
    <name>iohi</name>
    <type>oiouo</type>
    </position>
    <position id="900">
    <name>iohi1</name>
    <type>oiouo</type>
    </position>
    <position id="578">
    <name>jghj</name>
    <type>hkhjk</type>
    </position>

</positions>
